web/router.ex
defmodule StarWars.Router do
  use StarWars.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", StarWars do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    get "/starship_import", StarshipImportController, :new
    post "/starship_import", StarshipImportController, :import_starships
  end

  # Other scopes may use custom stacks.
  # scope "/api", StarWars do
  #   pipe_through :api
  # end
end

lib/star_wars/endpoint.ex
defmodule StarWars.Endpoint do
  use Phoenix.Endpoint, otp_app: :star_wars

  socket "/socket", StarWars.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :star_wars, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_star_wars_key",
    signing_salt: "cWoy6ycc"

  plug PryIn.Plug
  plug StarWars.Router
end

lib/star_wars/repo.ex
defmodule StarWars.Repo do
  use Ecto.Repo, otp_app: :star_wars
end

web/models/starship.ex
defmodule StarWars.Starship do
  use StarWars.Web, :model

  schema "starships" do
    field :name, :string
    field :model, :string
    field :manufacturer, :string

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:name, :model, :manufacturer])
    |> validate_required([:name, :model, :manufacturer])
  end
end

web/controllers/page_controller.ex
defmodule StarWars.PageController do
  use StarWars.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/controllers/starship_import_controller.ex
defmodule StarWars.StarshipImportController do
  use StarWars.Web, :controller
  require StarWars.Endpoint
  alias StarWars.Starship

  def new(conn, _params) do
    render conn, "new.html"
  end

  def import_starships(conn, %{"starship_ids" => starship_ids}) do
    parent_pid = self()
    starships = for starship_id <- String.split(starship_ids, ",") do
      Task.async(fn ->
        PryIn.join_trace(parent_pid, self())
        data = StarWars.Endpoint.instrument :pryin, %{key: "get_starship"}, fn ->
          HTTPoison.get!("http://swapi.co/api/starships/#{starship_id}/").body
          |> Poison.decode!
        end

        %Starship{}
        |> Starship.changeset(data)
        |> Repo.insert!()
      end)
    end
    |> Enum.map(&Task.await/1)

    render(conn, "import_starships.html", %{starships: starships})
  end
end

web/views/error_view.ex
defmodule StarWars.ErrorView do
  use StarWars.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule StarWars.LayoutView do
  use StarWars.Web, :view
end

web/views/page_view.ex
defmodule StarWars.PageView do
  use StarWars.Web, :view
end

web/views/starship_import_view.ex
defmodule StarWars.StarshipImportView do
  use StarWars.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello StarWars!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}", name: "Phoenix!" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

web/templates/starship_import/import_starships.html.eex
<h1>Starships imported</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Model</th>
      <th>Manufacturer</th>
    </tr>
  </thead>

  <tbody>
    <%= for starship <- @starships do %>
      <tr>
        <td><%= starship.name %></td>
        <td><%= starship.model %></td>
        <td><%= starship.manufacturer %></td>
      </tr>
    <% end %>
  </tbody>
</table>

web/templates/starship_import/new.html.eex
<h1>Import starships</h1>

<%= form_tag starship_import_path(@conn, :import_starships) do %>
  <div class="form-group">
    <label for="starship_ids">Starship ids</label>
    <input type="text" class="form-control" id="starhip_ids" name="starship_ids">
  </div>

  <button type="submit" class="btn btn-default">Submit</button>
<% end %>